// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: proto/orchestrator.proto

package orchestratorv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Orchestrator_ExecuteWorkflow_FullMethodName   = "/comfy.orchestrator.v1.Orchestrator/ExecuteWorkflow"
	Orchestrator_GetWorkflowStatus_FullMethodName = "/comfy.orchestrator.v1.Orchestrator/GetWorkflowStatus"
	Orchestrator_StreamStatus_FullMethodName      = "/comfy.orchestrator.v1.Orchestrator/StreamStatus"
	Orchestrator_ListNodes_FullMethodName         = "/comfy.orchestrator.v1.Orchestrator/ListNodes"
)

// OrchestratorClient is the client API for Orchestrator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrchestratorClient interface {
	ExecuteWorkflow(ctx context.Context, in *ExecuteWorkflowRequest, opts ...grpc.CallOption) (*ExecuteWorkflowResponse, error)
	GetWorkflowStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	StreamStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (Orchestrator_StreamStatusClient, error)
	ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error)
}

type orchestratorClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestratorClient(cc grpc.ClientConnInterface) OrchestratorClient {
	return &orchestratorClient{cc}
}

func (c *orchestratorClient) ExecuteWorkflow(ctx context.Context, in *ExecuteWorkflowRequest, opts ...grpc.CallOption) (*ExecuteWorkflowResponse, error) {
	out := new(ExecuteWorkflowResponse)
	err := c.cc.Invoke(ctx, Orchestrator_ExecuteWorkflow_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) GetWorkflowStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Orchestrator_GetWorkflowStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) StreamStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (Orchestrator_StreamStatusClient, error) {
	stream, err := c.cc.NewStream(ctx, &Orchestrator_ServiceDesc.Streams[0], Orchestrator_StreamStatus_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &orchestratorStreamStatusClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Orchestrator_StreamStatusClient interface {
	Recv() (*StatusEvent, error)
	grpc.ClientStream
}

type orchestratorStreamStatusClient struct {
	grpc.ClientStream
}

func (x *orchestratorStreamStatusClient) Recv() (*StatusEvent, error) {
	m := new(StatusEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *orchestratorClient) ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error) {
	out := new(ListNodesResponse)
	err := c.cc.Invoke(ctx, Orchestrator_ListNodes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrchestratorServer is the server API for Orchestrator service.
// All implementations must embed UnimplementedOrchestratorServer
// for forward compatibility
type OrchestratorServer interface {
	ExecuteWorkflow(context.Context, *ExecuteWorkflowRequest) (*ExecuteWorkflowResponse, error)
	GetWorkflowStatus(context.Context, *StatusRequest) (*StatusResponse, error)
	StreamStatus(*StatusRequest, Orchestrator_StreamStatusServer) error
	ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error)
	mustEmbedUnimplementedOrchestratorServer()
}

// UnimplementedOrchestratorServer must be embedded to have forward compatible implementations.
type UnimplementedOrchestratorServer struct {
}

func (UnimplementedOrchestratorServer) ExecuteWorkflow(context.Context, *ExecuteWorkflowRequest) (*ExecuteWorkflowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteWorkflow not implemented")
}
func (UnimplementedOrchestratorServer) GetWorkflowStatus(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkflowStatus not implemented")
}
func (UnimplementedOrchestratorServer) StreamStatus(*StatusRequest, Orchestrator_StreamStatusServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamStatus not implemented")
}
func (UnimplementedOrchestratorServer) ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNodes not implemented")
}
func (UnimplementedOrchestratorServer) mustEmbedUnimplementedOrchestratorServer() {}

// UnsafeOrchestratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrchestratorServer will
// result in compilation errors.
type UnsafeOrchestratorServer interface {
	mustEmbedUnimplementedOrchestratorServer()
}

func RegisterOrchestratorServer(s grpc.ServiceRegistrar, srv OrchestratorServer) {
	s.RegisterService(&Orchestrator_ServiceDesc, srv)
}

func _Orchestrator_ExecuteWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).ExecuteWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_ExecuteWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).ExecuteWorkflow(ctx, req.(*ExecuteWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_GetWorkflowStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).GetWorkflowStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_GetWorkflowStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).GetWorkflowStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_StreamStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrchestratorServer).StreamStatus(m, &orchestratorStreamStatusServer{stream})
}

type Orchestrator_StreamStatusServer interface {
	Send(*StatusEvent) error
	grpc.ServerStream
}

type orchestratorStreamStatusServer struct {
	grpc.ServerStream
}

func (x *orchestratorStreamStatusServer) Send(m *StatusEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _Orchestrator_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_ListNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).ListNodes(ctx, req.(*ListNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Orchestrator_ServiceDesc is the grpc.ServiceDesc for Orchestrator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Orchestrator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "comfy.orchestrator.v1.Orchestrator",
	HandlerType: (*OrchestratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteWorkflow",
			Handler:    _Orchestrator_ExecuteWorkflow_Handler,
		},
		{
			MethodName: "GetWorkflowStatus",
			Handler:    _Orchestrator_GetWorkflowStatus_Handler,
		},
		{
			MethodName: "ListNodes",
			Handler:    _Orchestrator_ListNodes_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamStatus",
			Handler:       _Orchestrator_StreamStatus_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/orchestrator.proto",
}

const (
	StageRunner_RunStage_FullMethodName = "/comfy.orchestrator.v1.StageRunner/RunStage"
	StageRunner_Health_FullMethodName   = "/comfy.orchestrator.v1.StageRunner/Health"
)

// StageRunnerClient is the client API for StageRunner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StageRunnerClient interface {
	RunStage(ctx context.Context, in *StageRequest, opts ...grpc.CallOption) (*StageResult, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type stageRunnerClient struct {
	cc grpc.ClientConnInterface
}

func NewStageRunnerClient(cc grpc.ClientConnInterface) StageRunnerClient {
	return &stageRunnerClient{cc}
}

func (c *stageRunnerClient) RunStage(ctx context.Context, in *StageRequest, opts ...grpc.CallOption) (*StageResult, error) {
	out := new(StageResult)
	err := c.cc.Invoke(ctx, StageRunner_RunStage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stageRunnerClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, StageRunner_Health_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StageRunnerServer is the server API for StageRunner service.
// All implementations must embed UnimplementedStageRunnerServer
// for forward compatibility
type StageRunnerServer interface {
	RunStage(context.Context, *StageRequest) (*StageResult, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedStageRunnerServer()
}

// UnimplementedStageRunnerServer must be embedded to have forward compatible implementations.
type UnimplementedStageRunnerServer struct {
}

func (UnimplementedStageRunnerServer) RunStage(context.Context, *StageRequest) (*StageResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunStage not implemented")
}
func (UnimplementedStageRunnerServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedStageRunnerServer) mustEmbedUnimplementedStageRunnerServer() {}

// UnsafeStageRunnerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StageRunnerServer will
// result in compilation errors.
type UnsafeStageRunnerServer interface {
	mustEmbedUnimplementedStageRunnerServer()
}

func RegisterStageRunnerServer(s grpc.ServiceRegistrar, srv StageRunnerServer) {
	s.RegisterService(&StageRunner_ServiceDesc, srv)
}

func _StageRunner_RunStage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StageRunnerServer).RunStage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StageRunner_RunStage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StageRunnerServer).RunStage(ctx, req.(*StageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StageRunner_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StageRunnerServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StageRunner_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StageRunnerServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StageRunner_ServiceDesc is the grpc.ServiceDesc for StageRunner service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StageRunner_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "comfy.orchestrator.v1.StageRunner",
	HandlerType: (*StageRunnerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunStage",
			Handler:    _StageRunner_RunStage_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _StageRunner_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/orchestrator.proto",
}
